# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Maddori.Apple Swift-Builder

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, release, hotfix, feature ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3        
    - name: MaddoriApple Build Tests
      run: |
        xcodebuild test -project ./Maddori.Apple/Maddori.Apple.xcodeproj -scheme Maddori.Apple -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0"
        xcpretty --color --simple
